language: node_js
node_js:
- "10"
script:
- echo "Deploy!!"
install:
- npm install -g firebase-tools
after_success:
- firabase deploy -project phonecard-d105b   - token 1/RozA1wTCtEe7FEVMKPPaYddJBqZ54ki4PhIV3oayPzrxgIX37fCAOvocEN8jgyiU
